services:
  memoryleak:
    build: .
    image: memoryleak
    container_name: memoryleak_container
    ports:
      - "5001:5001"
      - "5002:5002"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5001
      - DOTNET_EnableDiagnostics=1
    pid: "host"              
    cap_add:
      - SYS_PTRACE           
    tty: true 
    deploy:
      resources:
        limits:
          memory: 50M